easy_admin:
    site_name: '<img src="https://image.noelshack.com/fichiers/2018/20/4/1526560558-logovi.png"/>'
    design:
            brand_color: '#acb3b6'
            assets:
                favicon: 'https://image.noelshack.com/fichiers/2018/20/4/1526561943-white16.png'
                js:
                    - '/assets/ckeditor/ckeditor.js'
                    - '/assets/admin/admin.js'
    entities:
        # List the entity class name you want to manage
        Article:
            class: App\Entity\Article
            label: 'Articles'
            list:
                title: "Articles du blog"
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'createdAt', label: 'Date de création' }
            form:
                title: 'Modifier le contenu'
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'slug', label: 'URL Personnalisé' }
                    - { property: 'youtube', label: 'Youtube URL', type: 'text' }
                    - { property: 'content', label: 'Contenu', css_class: 'ckeditor', type: 'textarea' }
                    - { property: 'excerpt', label: 'Résumé', type: 'text' }
                    - { property: 'createdAt', label: 'Date de création' }
                    - { property: 'updatedAt', label: 'Dernière mise à jour' }
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                title: "Liste des administrateurs"
                fields:
                    - { property: 'username', label: 'Nom' }
                    - { property: 'email', label: 'E-mail' }
            form:
                title: 'Modifier le compte'
                fields:
                    - { property: 'username', label: 'Nom' }
                    - { property: 'email', type: 'email', label: 'E-mail' }
                    - { property: 'plainPassword', type: 'password', label: 'Mot de passe' }
                    - { property: 'isActive', type: 'checkbox', label: 'Active ?' }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true }}
        Comment:
            class: App\Entity\Comment
            label: 'Commentaires'
            list:
                title: "Commentaires publiés"
                fields:
                    - { property: 'created', label: 'Date de publication' }
                    - { property: 'content', label: 'Contenu'}
            form:
                title: 'Modifier un commentaire'
                fields:
                    - { property: 'content', label: 'Contenu', type: 'textarea'}

        Contact:
            class: App\Entity\Contact
            label: 'Messages reçus'
            list:
                title: 'Messages reçus'
                fields:
                    - { property: 'created', label: 'Date de réception' }
                    - { property: 'email', label: 'E-mail du contact' }
                    - { property: 'subject', label: 'Sujet du message'}
                    - { property: 'message', label: 'Contenu du message' }
            form:
                title: 'Détails des messages'
                fields:
                    - { property: 'email', label: 'E-mail du contact' }
                    - { property: 'subject', label: 'Sujet du message'}
                    - { property: 'message', label: 'Contenu du message', type: 'textarea' }


