easy_admin:
    site_name: 'Vinci Investments Blog'
    entities:
        # List the entity class name you want to manage

        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email', label: 'E-mail' }
                    - { property: 'plainPassword', type: 'password', label: 'Password' }
                    - { property: 'isActive', type: 'checkbox', label: 'Active ?' }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true }}
        Article:
            class: App\Entity\Article

    design:
        brand_color: '#670000'